defaultSettings:
  defaultReplicaCount: 2
  storageMinimalAvailablePercentage: 10

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m
