grafana:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi
  adminPassword: "admin"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.173.249.57.192.sslip.io
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.173.249.57.192.sslip.io
prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'telegram'
    receivers:
      - name: 'telegram'
        telegram_configs:
          - bot_token: '8564917508:AAHwt1XFnajnPVxWkNCy3a9gI9htujyQ7R0'
            chat_id: 1620259665
            parse_mode: 'HTML'
            massage: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true
