apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: argocd-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: argocd/admin
        property: password
