apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: telegram-credentials
    creationPolicy: Owner
  data:
    - secretKey: bot_token
      remoteRef:
        key: monitoring/telegram
        property: bot_token
    - secretKey: chat_id
      remoteRef:
        key: monitoring/telegram
        property: chat_id
