controller:
  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$remote_addr", "method": "$request_method", "path": "$uri", "status": $status, "response_time": $request_time, "user_agent": "$http_user_agent", "referer": "$http_referer", "host": "$host"}'
  service:
    type: NodePort
  hostNetwork: true
  kind: DaemonSet
  ingressClassResource:
    name: nginx
    default: true
