config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      tenant_id: fake

  snippets:
    piplineStages:
      - cri: {}
      - match:
        selector: '{namespace="ingerss-nginx"}'
        stages:
          - json:
              expressions:
                path: path
                method: method
                status: status
                remote_addr: remote_addr
                response_time: response_time
                host: host
                user_agent: user_aget
        - labels:
            method:
            status:
            host:

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 100m

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
