config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      tenant_id: fake

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 100m

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
